vim.pack.add({
  -- { src = "https://github.com/vague2k/vague.nvim" },
  -- { src = "https://github.com/catppuccin/nvim" },
  -- { src = "https://github.com/folke/tokyonight.nvim" },
  { src = "https://github.com/ellisonleao/gruvbox.nvim" },
  { src = "https://github.com/nvim-lua/plenary.nvim" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter",          version = "main" },
  { src = "https://github.com/nvim-telescope/telescope.nvim",            version = "0.1.8" },
  { src = "https://github.com/ThePrimeagen/harpoon",                     version = "harpoon2" },
  { src = "https://github.com/neovim/nvim-lspconfig" },
  { src = "https://github.com/mason-org/mason.nvim" },
  { src = "https://github.com/rafamadriz/friendly-snippets" },
  { src = "https://github.com/saghen/blink.cmp",                         version = vim.version.range("^1") },
  { src = "https://github.com/j-hui/fidget.nvim" },
  { src = "https://github.com/folke/trouble.nvim" },
  { src = "https://github.com/L3MON4D3/LuaSnip" },
  { src = "https://github.com/christoomey/vim-tmux-navigator" },
  { src = "https://github.com/nvim-tree/nvim-web-devicons" },
  { src = "https://github.com/laytan/cloak.nvim" },
  { src = "https://github.com/mbbill/undotree" },
  { src = "https://github.com/nvim-lualine/lualine.nvim" },
  { src = "https://github.com/stevearc/conform.nvim" },
  { src = "https://github.com/MeanderingProgrammer/render-markdown.nvim" },
  -- { src = "https://github.com/chentoast/marks.nvim" },
})
